### ISSUE TITLE
iOS9

### ISSUE THREAD

**Issue by tsabicheck** [psutlt/mirrorapp#2]
Does it work with iOS9? I tried, but can't connect. Thanks!

**Comment by jasonheffner** [comment]
I'll push out an update for iOS9 this week. Sorry for the delay as I was testing the code internal with our version to make sure it works correctly.

**Comment by jasonheffner** [comment]
iOS9 and AppleTV5 support added. You will also want to update from the mirrorapp-server code. AirServer no longer works though as they are enforcing the private key matching. AppleTV still is not enforcing this on the AppleTV5 currently, or older models.

**Comment by tsabicheck** [comment]
Thanks so much Jason!
