### ISSUE TITLE
local. host name not resolved

### ISSUE THREAD

**Issue by nix1024** [psutlt/mirrorapp#3]
Hi,

I am doing the same thing right now. I ask my question here since I have no other way, sorry if it's inappropriate.

After registering the airplay & raop service, my AirPlay service did show in control center, but no A record found in MDNS query response in Wireshark, thus the phone can not connect to Apple TV.

How to add A record for my host name of Airplay service? 

Thanks for you efforts.

**Comment by jasonheffner** [comment]
The AppleTV needs to have a valid DNS entry that can resolve to a fqdn (i.e. - myappletv.mydns.somewhere.com) that the iPhone can resolve. The standard method everyone uses to register a Service is [DNSServiceRegister](https://developer.apple.com/library/content/documentation/Networking/Conceptual/dns_discovery_api/Articles/registering.html) which requires a hostname to be provided and then does a reverse DNS lookup for. I thought, perhaps, at one time it would be advantageous to register this DNS entry local on the device but we aren't actively developing the project anymore.

**Comment by nix1024** [comment]
I've got this working by adding A record with `DNSServiceAddRecord` for my host, thanks a lot.

**Comment by jasonheffner** [comment]
Yep, that would work
